### ISSUE TITLE
p2p code review

### ISSUE THREAD

**Issue by nyatindopatrick** [nyatindopatrick/tic-tac-toe#6]
Please leave some comments.

**Comment by rammazzoti2000** [comment]
game_logic branch should have at least two files in lib directory. You could use `display_board` method from `game_logic.rb` to create a new class.

**Comment by adamclasic** [comment]
No issues good work

**Comment by Kyle-Law** [comment]
Great user interface! The only issue would probably be the multi-responsibilities of your method, especially `win_moves(player)`. Try to refactor it to adhere to the single responsibility rule, in which each method only handles a single function. 

Apart from that, your tictactoe looks good 👍

**Comment by dili021** [comment]
- I think a TSE will call you out on Encapsulation and S(ingle responsibility)OLID (which happened to me). Your whole main file has open loops and methods which need to be wrapped in a class.
- Also, when the time comes for RSpec, which is the next project, you will need to make test cases for every method in your game. That will be impossible unless you're methods follow the SOLID principle. Our first version looked similar to yours.
- Dissect your methods to the smallest bytes possible, it will make your life much easier when you get to testing. Trust me, I'm battling with tic tac toe and it's testing for 2 weeks...

**Comment by patriciachrysy** [comment]
Good job Patrick!!! I agree with Kyle, that method is not even supposed to be there. Try to use one class to manage a single thing, like if you are managing the board only, give him methods to check if the board if full or if a spot is taken, give him an attribute containing the winning combination that is immutable. Do not make him check if there is a winner or not, that should be managed inside another class which can be named Game or GameLogic. 
Also, a small tip, use a Player class to manage your players and store the position of their chosen spot all along, this will make the check_winner function way smaller. Having more classes and less code in main will make it much easier for you to do the spec later.

**Comment by nyatindopatrick** [comment]
Thank for the comments.
